site_name: UTEDocs
site_author: Feafly
site_description: 这是一个由Feafly制作的用于“Undertale Engine”及其扩展的参考文档
copyright: Ceyase/Feafly TML233 TobyFox
nav:
  - 主页: index.md
  - 新手入门:
    - 新手入门\1.食用须知.md
    - 新手入门\2.准备工作.md
  - 基本命令:
    - Battle:
      - 基本命令\Battle\Board.md
      - 基本命令\Battle\Bullet.md
      - 基本命令\Battle\Dialog.md
      - 基本命令\Battle\Enemy.md
      - 基本命令\Battle\Menu.md
      - 基本命令\Battle\Player.md
      - 基本命令\Battle\Reward.md
      - 基本命令\Battle\Soul.md
      - 基本命令\Battle\State.md
      - 基本命令\Battle\Turn.md
      - 基本命令\Battle\其他函数.md
    - Player:
      - 基本命令\Player\LV操作命令.md
      - 基本命令\Player\基础命令.md
      - 基本命令\Player\玩家属性操作命令.md
    - 基本命令\BGM.md
    - 基本命令\Border.md
    - 基本命令\Box.md
    - 基本命令\CC.md
    - 基本命令\Demo.md
    - 基本命令\Dialog.md
    - 基本命令\Encounter.md
    - 基本命令\Flag.md
    - 基本命令\Game.md
    - 基本命令\Item.md
    - 基本命令\Macro.md
    - 基本命令\Phone.md
    - 基本命令\其他命令.md
  - 游戏实践:
    - Help_Tale: 游戏实践\1.Help_Tale.md
  - Gamemaker帮助文档:
    - Gamemaker帮助文档\01-Gamemaker Studio2帮助文档.md
    - Gamemaker帮助文档\02-关于GMS2登录账号总是卡死的问题.md
  - 云游戏:
    - Sans模拟器: 云游戏\01-sans模拟器.md
    - 柯罗诺斯战: 云游戏\02-柯罗诺斯战.md
  - 论坛传说: http://47.97.5.211:7002
  - 天机云存储: http://47.97.5.211:7000
  - 天机游戏: http://47.97.5.211:7001
  
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences 

